export enum ERROR_MESSAGES {

    INTERNAL_SERVER_ERROR="An unexpected error occurred. Please try again later.",
    BAD_REQUEST= "The request could not be understood or was missing required parameters.",
    UNAUTHORIZED= "You are not authorized to access this resource.",
    FORBIDDEN= "You are not allowed to perform this action.",
    NOT_FOUND= "The requested resource could not be found.",
    INVALID_INPUT= "The request contains invalid data.",
    UPDATION_FAILED = "Unable to update data",
    DUPLICATE_DATA= "Data already exist",
    USER_NOT_FOUND = "user not found",
    EXPERT_REJECTED ="expert rejected",
    UNABLE_UPDATION = "unable to update data" ,
    UNABLE_FETCH = "unable to fetch data",
    USER_ALREADY_EXIST ="user already exist. please signIn",
    BLOCKD_USER = "user is blocked",
    INCORRECT_PASSWORD ="incorrect password",
    OTP_EXPIRED = "OTP Expired. Try again",
    INCORRECT_OTP = "Incorrect OTP. Please try again",
    UNABLE_FIND_USER ='unbale to find the account please signup',
    UNABLE_SIGNUP = "unable to signup. Try again",
    INVALID_MEETING = "Invalid meeting",
    UNABLE_TO_CREATE = "unable to create record",
    PAYMENT_VERIFICATION_FAILED = "Payment verification failed",
    WALLET_EMPTY = "Your wallet is empty",
    INVALID_AMOUNT = "Invalid amount",
    FAILED_DELETION = "unable to delete record",
    ERROR_CREATE_CHAT_USER = "user data is empty, unable to create new chat",
    ERROR_CREATE_CHAT_EXPERT = "expert data is empty, unable to create new chat",
    ERROR_CHAT_CREATION = "unable to create chat",
    IMAGE_UPLOAD_FAILED = "Failed to upload image",
    INVALID_USER = "Invalid user",
    ERROR_SENDING_OTP = "Failed to send verification email",
    REFRESH_TOKEN_NOT_FOUND = "Refresh token not found",
    INVALID_REFRESH ="Invalid refresh token"
}